### ISSUE TITLE
Arreglar migraciones.

### ISSUE THREAD

**Issue by aranajhonny** [TeamCriollo/zogam#14]
Hay que tratar de arreglar las migraciones para poder integrar con postgres (Solo para probar) lo mas seguro es que usemos mysql pero igual hay que hacer esto.

**Comment by OswardJr** [comment]
Vamos con eso

**Comment by aranajhonny** [comment]
hay que guiarse por esta version https://gist.github.com/aranajhonny/6da428f1c837233a0e790db0b009fc85
