### ISSUE TITLE
Agregar validacion del lado  del servidor en cuanto al anio y la placa.

### ISSUE THREAD

**Issue by aranajhonny** [TeamCriollo/zogam#4]

**Comment by aranajhonny** [comment]
@OswardJr encargate de eso ahi.

**Comment by OswardJr** [comment]
[https://github.com/OswardJr/zogam/commit/85ca9e0098dd6e39d77a1b9678b5433fadbfda5f](url)

Te dejo el link mientras actualizo la rama..

**Comment by aranajhonny** [comment]
@OswardJr  te recomiendo vuelvas a hacer fork y clonar otra vez en tu maquina
