### ISSUE TITLE
Falta validación de letras o numeros

### ISSUE THREAD

**Issue by aranajhonny** [TeamCriollo/zogam#5]

**Comment by OswardJr** [comment]
Voy con eso, in process

**Comment by OswardJr** [comment]
Ya cloné

**Comment by OswardJr** [comment]
[e5a5a25c4e32ed561208790c28e35acf180934b2](url)

**Comment by OswardJr** [comment]
Los validaré todos..

**Comment by OswardJr** [comment]
[e5a5a25c4e32ed561208790c28e35acf180934b2](url)

New versión.
